// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.startupRolloutPrefs.fission.experiment.enrollmentStatus", 4);
user_pref("app.normandy.startupRolloutPrefs.media.peerconnection.mtransport_process", true);
user_pref("app.normandy.startupRolloutPrefs.network.process.enabled", true);
user_pref("app.normandy.user_id", "2cdf4d27-8f27-459c-b5d1-8287c9d91fd5");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1641326383);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1641326382);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{ee6b6419-b859-407d-9077-34fd90d886cb}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1641326380);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 120);
user_pref("browser.newtabpage.activity-stream.impressionId", "{4878085e-c5b0-4b8d-bdfa-053158f9011e}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1641326382);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1641326383721");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1641347983721");
user_pref("browser.search.region", "US");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1641326381");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20211215221728");
user_pref("browser.startup.homepage_override.mstone", "95.0.1");
user_pref("browser.startup.homepage_override.once", "{\"message_id\":\"WNP_MOMENTS_13\",\"url\":\"https://www.mozilla.org/firefox/welcome/13\",\"expire\":1640908800000}");
user_pref("browser.startup.lastColdStartupCheck", 1641326381);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"_48748554-4c01-49e8-94af-79662bf34d50_-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\",\"_48748554-4c01-49e8-94af-79662bf34d50_-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 1);
user_pref("browser.urlbar.quicksuggest.scenario", "offline");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1641326382310");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "95.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "US");
user_pref("dom.push.userAgentID", "7a3cd847b9db4607b9c8a2b5f1b16841");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.cache.lastUpdate", 1641326382);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20211215221728");
user_pref("extensions.lastAppVersion", "95.0.1");
user_pref("extensions.lastPlatformVersion", "95.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"c1d7d32f-0ed6-491e-bb53-9bdec0e3ac19\",\"formautofill@mozilla.org\":\"6c94d711-356a-4261-ab0b-f503bd6581fb\",\"pictureinpicture@mozilla.org\":\"2281990b-133e-4ba2-98b4-9dc6219550a1\",\"proxy-failover@mozilla.com\":\"1c205653-ca2f-46ce-b0ec-c9472795d575\",\"screenshots@mozilla.org\":\"2a7831d1-ae9f-4809-b13b-1c980ee96b83\",\"webcompat-reporter@mozilla.org\":\"46a74d01-ee08-41d2-a608-20014d9ba5b9\",\"webcompat@mozilla.org\":\"235bdf02-c6b7-44dd-b5da-45d0eb4c9834\",\"default-theme@mozilla.org\":\"df7f6bd1-6c94-45b2-90cc-8af33797ad54\",\"addons-search-detection@mozilla.com\":\"af39239c-7634-4a96-bb53-ec65fdf53517\",\"google@search.mozilla.org\":\"a1be5d8b-a519-4d41-b3bf-d9c3a0d2e5fc\",\"amazondotcom@search.mozilla.org\":\"483008ce-c255-4b25-a386-d2f2aa4a8a62\",\"wikipedia@search.mozilla.org\":\"6690f5b4-7222-4e74-a176-a9ca423062ff\",\"bing@search.mozilla.org\":\"365c0138-b757-4fe2-8d08-d1d081d69ffa\",\"ddg@search.mozilla.org\":\"13e07a38-333c-4110-854c-f09237610562\",\"ebay@search.mozilla.org\":\"64639da7-4ada-46ee-b80c-7408d2f9c7cd\",\"{48748554-4c01-49e8-94af-79662bf34d50}\":\"768697dc-aaed-4642-a287-896bcf743f74\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1641326382);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("fission.experiment.startupEnrollmentStatus", 4);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "08468f6f-c639-43b6-a714-bdd1493dabc5");
user_pref("toolkit.startup.last_success", 1641326379);
user_pref("toolkit.telemetry.cachedClientID", "db1e1a34-a1e2-4a17-b38c-98e6f90bc0a0");
user_pref("toolkit.telemetry.previousBuildID", "20211215221728");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
